services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - ./backend/uploads:/app/uploads
      - ./backend/.env:/app/.env
    environment:
      - PYTHONUNBUFFERED=1
      - REDIS_URL=redis://redis:6379
      - TIKA_SERVER_URL=http://tika:9998
    depends_on:
      - redis
      - tika
    restart: unless-stopped

  # Worker de Celery para procesamiento asíncrono (optimizado para desarrollo con 3GB WSL)
  celery-worker:
    build:
      context: ./backend
      dockerfile: Dockerfile
    command: /venv/bin/celery -A celery_app worker --loglevel=info --concurrency=1 --max-tasks-per-child=5 --max-memory-per-child=250000 --pool=solo
    volumes:
      - ./backend:/app
      - ./backend/uploads:/app/uploads
      - ./backend/.env:/app/.env
      - ./backend/models:/app/models
    environment:
      - PYTHONUNBUFFERED=1
      - REDIS_URL=redis://redis:6379
      - TIKA_SERVER_URL=http://tika:9998
    depends_on:
      - redis
      - tika
      - backend
    restart: unless-stopped

  tika:
    build:
      context: ./backend
      dockerfile: Dockerfile.tika
    ports:
      - "9998:9998"
    restart: unless-stopped
    environment:
      - TIKA_SERVER_OPTS=-Xmx512m -Xms256m

  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped
    command: redis-server --maxmemory 256mb --maxmemory-policy allkeys-lru

volumes:
  redis_data:
