version: '3.9'

services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      - ./backend/uploads:/app/uploads
      - ./backend/.env:/app/.env
    environment:
      - PYTHONUNBUFFERED=1
    depends_on:
      - redis
      - tika
  tika:
    build:
      context: ./backend
      dockerfile: Dockerfile.tika
    ports:
      - "9998:9998"
    restart: unless-stopped
    environment:
      - NODE_ENV=development
  redis:
    image: redis:7-alpine
    ports:
      - "6379:6379"
    volumes:
      - redis_data:/data
    restart: unless-stopped

volumes:
  redis_data:
