"""agregar_campo_ruta_archivo_a_documento

Revision ID: a6132e715c2f
Revises: dcf1a6c84751
Create Date: 2025-09-03 14:50:25.671024

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a6132e715c2f'
down_revision: Union[str, Sequence[str], None] = 'dcf1a6c84751'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('T_Documento', sa.Column('CT_Ruta_archivo', sa.String(length=500), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('T_Documento', 'CT_Ruta_archivo')
    # ### end Alembic commands ###
