"""Base de datos inicial

Revision ID: bf72e9a43bee
Revises: 
Create Date: 2025-09-04 14:28:19.637539

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf72e9a43bee'
down_revision: Union[str, Sequence[str], None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('T_Estado',
    sa.Column('CN_Id_estado', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('CT_Nombre_estado', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('CN_Id_estado'),
    sa.UniqueConstraint('CT_Nombre_estado')
    )
    op.create_table('T_Estado_procesamiento',
    sa.Column('CN_Id_estado', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('CT_Nombre_estado', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('CN_Id_estado'),
    sa.UniqueConstraint('CT_Nombre_estado')
    )
    op.create_table('T_Expediente',
    sa.Column('CN_Id_expediente', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('CT_Num_expediente', sa.String(length=60), nullable=False),
    sa.Column('CF_Fecha_creacion', sa.DateTime(), nullable=False),
    sa.PrimaryKeyConstraint('CN_Id_expediente'),
    sa.UniqueConstraint('CT_Num_expediente', name='uq_expediente_num')
    )
    op.create_table('T_Rol',
    sa.Column('CN_Id_rol', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('CT_Nombre_rol', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('CN_Id_rol'),
    sa.UniqueConstraint('CT_Nombre_rol')
    )
    op.create_table('T_Tipo_accion',
    sa.Column('CN_Id_tipo_accion', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('CT_Nombre_tipo_accion', sa.String(length=50), nullable=False),
    sa.PrimaryKeyConstraint('CN_Id_tipo_accion'),
    sa.UniqueConstraint('CT_Nombre_tipo_accion')
    )
    op.create_table('T_Documento',
    sa.Column('CN_Id_documento', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('CT_Nombre_archivo', sa.String(length=255), nullable=False),
    sa.Column('CT_Tipo_archivo', sa.String(length=50), nullable=False),
    sa.Column('CT_Ruta_archivo', sa.String(length=500), nullable=True),
    sa.Column('CF_Fecha_carga', sa.DateTime(), nullable=False),
    sa.Column('CN_Id_estado', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['CN_Id_estado'], ['T_Estado_procesamiento.CN_Id_estado'], ),
    sa.PrimaryKeyConstraint('CN_Id_documento')
    )
    op.create_table('T_Usuario',
    sa.Column('CN_Id_usuario', sa.String(length=20), autoincrement=False, nullable=False),
    sa.Column('CT_Nombre_usuario', sa.String(length=50), nullable=False),
    sa.Column('CT_Nombre', sa.String(length=100), nullable=False),
    sa.Column('CT_Apellido_uno', sa.String(length=100), nullable=False),
    sa.Column('CT_Apellido_dos', sa.String(length=100), nullable=True),
    sa.Column('CT_Correo', sa.String(length=100), nullable=False),
    sa.Column('CT_Contrasenna', sa.String(length=255), nullable=False),
    sa.Column('CN_Id_rol', sa.Integer(), nullable=True),
    sa.Column('CN_Id_estado', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['CN_Id_estado'], ['T_Estado.CN_Id_estado'], ),
    sa.ForeignKeyConstraint(['CN_Id_rol'], ['T_Rol.CN_Id_rol'], ),
    sa.PrimaryKeyConstraint('CN_Id_usuario'),
    sa.UniqueConstraint('CT_Correo', name='uq_usuario_correo'),
    sa.UniqueConstraint('CT_Nombre_usuario', name='uq_usuario_nombre')
    )
    op.create_table('T_Bitacora',
    sa.Column('CN_Id_bitacora', sa.BigInteger(), autoincrement=True, nullable=False),
    sa.Column('CF_Fecha_hora', sa.DateTime(), nullable=False),
    sa.Column('CT_Texto', sa.Text(), nullable=False),
    sa.Column('CT_Informacion_adicional', sa.Text(), nullable=True),
    sa.Column('CN_Id_usuario', sa.String(length=20), nullable=False),
    sa.Column('CN_Id_tipo_accion', sa.Integer(), nullable=True),
    sa.Column('CN_Id_expediente', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['CN_Id_expediente'], ['T_Expediente.CN_Id_expediente'], ),
    sa.ForeignKeyConstraint(['CN_Id_tipo_accion'], ['T_Tipo_accion.CN_Id_tipo_accion'], ),
    sa.ForeignKeyConstraint(['CN_Id_usuario'], ['T_Usuario.CN_Id_usuario'], ),
    sa.PrimaryKeyConstraint('CN_Id_bitacora')
    )
    op.create_table('T_Expediente_Documento',
    sa.Column('CN_Id_expediente', sa.BigInteger(), nullable=False),
    sa.Column('CN_Id_documento', sa.BigInteger(), nullable=False),
    sa.ForeignKeyConstraint(['CN_Id_documento'], ['T_Documento.CN_Id_documento'], ),
    sa.ForeignKeyConstraint(['CN_Id_expediente'], ['T_Expediente.CN_Id_expediente'], ),
    sa.PrimaryKeyConstraint('CN_Id_expediente', 'CN_Id_documento')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('T_Expediente_Documento')
    op.drop_table('T_Bitacora')
    op.drop_table('T_Usuario')
    op.drop_table('T_Documento')
    op.drop_table('T_Tipo_accion')
    op.drop_table('T_Rol')
    op.drop_table('T_Expediente')
    op.drop_table('T_Estado_procesamiento')
    op.drop_table('T_Estado')
    # ### end Alembic commands ###
