"""agregar_campos_fecha_usuario

Revision ID: c039f8f03469
Revises: fd0682745253
Create Date: 2025-09-08 13:03:15.589349

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c039f8f03469'
down_revision: Union[str, Sequence[str], None] = 'fd0682745253'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('T_Usuario', sa.Column('CF_Ultimo_acceso', sa.DateTime(), nullable=True))
    op.add_column('T_Usuario', sa.Column('CF_Fecha_creacion', sa.DateTime(), nullable=False, server_default=sa.func.now()))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('T_Usuario', 'CF_Fecha_creacion')
    op.drop_column('T_Usuario', 'CF_Ultimo_acceso')
    # ### end Alembic commands ###
