@startuml
left to right direction

skinparam backgroundColor white
skinparam actorStyle awesome
skinparam usecase {
  BackgroundColor #EAF1F8
  BorderColor #1F4E79
  FontColor #1F4E79
}
skinparam actor {
  BorderColor #1F4E79
  FontColor #1F4E79
}
skinparam rectangle {
  BorderColor #1F4E79
  FontColor #1F4E79
  FontStyle bold
}
skinparam ArrowColor #1F4E79
skinparam packageStyle rectangle

actor "Usuario Gubernamental" as UG
rectangle "Sistema ServIA" {
  usecase "Previsualizar Documento Original" as CU12
  usecase "Verificar pertenencia del documento" as S1
  usecase "Recuperar archivo original" as S2
}
UG --> CU12
CU12 ..> S1 : <<include>>
CU12 ..> S2 : <<include>>
@enduml